package control;

import adt.ArrayBucketList;
import entity.Consultation;
import entity.Patient;
import entity.Doctor;
import dao.ConsultationDao;
import java.util.Date;
import java.util.Iterator;

/**
 * @author: Poh Qi Xuan
 * Consultation Management Control - Module 3
 * Manages patient consultations and arrange subsequent visit appointments
 */
public class ConsultationManagementControl {
    
    private ArrayBucketList<String, Consultation> consultations;
    private ArrayBucketList<String, Consultation> scheduledConsultations;
    private ConsultationDao consultationDao;
    
    public ConsultationManagementControl() {
        this.consultations = new ArrayBucketList<String, Consultation>();
        this.scheduledConsultations = new ArrayBucketList<String, Consultation>();
        this.consultationDao = new ConsultationDao();
        loadConsultationData();
    }
    
    public void loadConsultationData() {
        try {
            consultations = consultationDao.findAll();
            Iterator<Consultation> consultationIterator = consultations.iterator();
            while (consultationIterator.hasNext()) {
                Consultation consultation = consultationIterator.next();
                if (consultation.getStatus() == Consultation.ConsultationStatus.SCHEDULED) {
                    scheduledConsultations.add(consultation.getConsultationId(), consultation);
                }
            }
        } catch (Exception exception) {
            System.err.println("Error loading consultation data: " + exception.getMessage());
        }
    }
    
    // Consultation Management Methods
    public boolean scheduleConsultation(Patient patient, Doctor doctor, 
                                      Date consultationDate, String symptoms, 
                                      double consultationFee) {
        try {
            // Create new consultation without ID (will be generated by database)
            Consultation consultation = new Consultation(null, patient, doctor, 
                                                       consultationDate, symptoms, consultationFee);
            
            // Insert consultation and get the generated ID
            boolean consultationInserted = consultationDao.insertAndReturnId(consultation);
            if (!consultationInserted) {
                System.err.println("Failed to insert consultation");
                return false;
            }
            
            // Add to lists
            consultations.add(consultation.getConsultationId(), consultation);
            scheduledConsultations.add(consultation.getConsultationId(), consultation);
            
            // Add to doctor's appointment list
            doctor.addAppointment(null); // We'll need to create an Appointment entity
            
            return true;
        } catch (Exception exception) {
            System.err.println("Error scheduling consultation: " + exception.getMessage());
            return false;
        }
    }
    
    public boolean startConsultation(String consultationId) {
        try {
            Consultation consultation = findConsultationById(consultationId);
            if (consultation != null && consultation.getStatus() == Consultation.ConsultationStatus.SCHEDULED) {
                consultation.setStatus(Consultation.ConsultationStatus.IN_PROGRESS);
                return true;
            }
            return false;
        } catch (Exception exception) {
            System.err.println("Error starting consultation: " + exception.getMessage());
            return false;
        }
    }
    
    public boolean completeConsultation(String consultationId, String diagnosis, 
                                      String treatment, String notes, Date nextVisitDate) {
        try {
            Consultation consultation = findConsultationById(consultationId);
            if (consultation != null && consultation.getStatus() == Consultation.ConsultationStatus.IN_PROGRESS) {
                consultation.setDiagnosis(diagnosis);
                consultation.setTreatment(treatment);
                consultation.setNotes(notes);
                consultation.setNextVisitDate(nextVisitDate);
                consultation.setStatus(Consultation.ConsultationStatus.COMPLETED);
                
                // Remove from scheduled consultations
                removeFromScheduledConsultations(consultation);
                
                return true;
            }
            return false;
        } catch (Exception exception) {
            System.err.println("Error completing consultation: " + exception.getMessage());
            return false;
        }
    }
    
    public boolean cancelConsultation(String consultationId) {
        try {
            Consultation consultation = findConsultationById(consultationId);
            if (consultation != null && consultation.getStatus() == Consultation.ConsultationStatus.SCHEDULED) {
                consultation.setStatus(Consultation.ConsultationStatus.CANCELLED);
                
                // Remove from scheduled consultations
                removeFromScheduledConsultations(consultation);
                
                return true;
            }
            return false;
        } catch (Exception exception) {
            System.err.println("Error cancelling consultation: " + exception.getMessage());
            return false;
        }
    }
    
    // Search and Retrieval Methods
    public Consultation findConsultationById(String consultationId) {
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getConsultationId().equals(consultationId)) {
                return consultation;
            }
        }
        return null;
    }
    
    public ArrayBucketList<String, Consultation> findConsultationsByPatient(String patientId) {
        ArrayBucketList<String, Consultation> patientConsultations = new ArrayBucketList<String, Consultation>();
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getPatient().getPatientId().equals(patientId)) {
                patientConsultations.add(consultation.getConsultationId(), consultation);
            }
        }
        return patientConsultations;
    }
    
    public ArrayBucketList<String, Consultation> findConsultationsByDoctor(String doctorId) {
        ArrayBucketList<String, Consultation> doctorConsultations = new ArrayBucketList<String, Consultation>();
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getDoctor().getDoctorId().equals(doctorId)) {
                doctorConsultations.add(consultation.getConsultationId(), consultation);
            }
        }
        return doctorConsultations;
    }
    
    public ArrayBucketList<String, Consultation> findConsultationsByDate(Date date) {
        ArrayBucketList<String, Consultation> dateConsultations = new ArrayBucketList<String, Consultation>();
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getConsultationDate().equals(date)) {
                dateConsultations.add(consultation.getConsultationId(), consultation);
            }
        }
        return dateConsultations;
    }
    
    public ArrayBucketList<String, Consultation> getScheduledConsultations() {
        return scheduledConsultations;
    }
    
    public ArrayBucketList<String, Consultation> getCompletedConsultations() {
        ArrayBucketList<String, Consultation> completedConsultations = new ArrayBucketList<String, Consultation>();
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getStatus() == Consultation.ConsultationStatus.COMPLETED) {
                completedConsultations.add(consultation.getConsultationId(), consultation);
            }
        }
        return completedConsultations;
    }
    
    public ArrayBucketList<String, Consultation> getAllConsultations() {
        return consultations;
    }
    
    public int getTotalConsultations() {
        return consultations.getSize();
    }
    
    public int getScheduledConsultationsCount() {
        return scheduledConsultations.getSize();
    }
    
    // Reporting Methods
    public String generateConsultationReport() {
        StringBuilder report = new StringBuilder();
        report.append("=== CONSULTATION REPORT ===\n");
        report.append("Total Consultations: ").append(getTotalConsultations()).append("\n");
        report.append("Scheduled Consultations: ").append(getScheduledConsultationsCount()).append("\n");
        report.append("Completed Consultations: ").append(getCompletedConsultations().getSize()).append("\n");
        report.append("Report Generated: ").append(new Date()).append("\n\n");
        
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            report.append("Consultation ID: ").append(consultation.getConsultationId()).append("\n");
            report.append("Patient: ").append(consultation.getPatient().getFullName()).append("\n");
            report.append("Doctor: ").append(consultation.getDoctor().getFullName()).append("\n");
            report.append("Date: ").append(consultation.getConsultationDate()).append("\n");
            report.append("Status: ").append(consultation.getStatus()).append("\n");
            report.append("Fee: RM").append(consultation.getConsultationFee()).append("\n");
            report.append("----------------------------------------\n");
        }
        
        return report.toString();
    }
    
    public String generateConsultationHistoryReport() {
        StringBuilder report = new StringBuilder();
        report.append("=== CONSULTATION HISTORY REPORT ===\n");
        report.append("Total Consultations: ").append(getTotalConsultations()).append("\n");
        report.append("Completed Consultations: ").append(getCompletedConsultations().getSize()).append("\n");
        report.append("Report Generated: ").append(new Date()).append("\n\n");
        
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getStatus() == Consultation.ConsultationStatus.COMPLETED) {
                report.append("Consultation ID: ").append(consultation.getConsultationId()).append("\n");
                report.append("Patient: ").append(consultation.getPatient().getFullName()).append("\n");
                report.append("Doctor: ").append(consultation.getDoctor().getFullName()).append("\n");
                report.append("Date: ").append(consultation.getConsultationDate()).append("\n");
                report.append("Status: ").append(consultation.getStatus()).append("\n");
                report.append("Fee: RM").append(consultation.getConsultationFee()).append("\n");
                report.append("----------------------------------------\n");
            }
        }
        
        return report.toString();
    }
    
    private void removeFromScheduledConsultations(Consultation consultation) {
        Iterator<Consultation> scheduledIterator = scheduledConsultations.iterator();
        while (scheduledIterator.hasNext()) {
            Consultation scheduledConsultation = scheduledIterator.next();
            if (scheduledConsultation.getConsultationId().equals(consultation.getConsultationId())) {
                scheduledConsultations.remove(scheduledConsultation.getConsultationId());
                break;
            }
        }
    }
} 