package control;

import adt.ArrayBucketList;
import entity.Consultation;
import entity.Patient;
import entity.Doctor;
import entity.Schedule;
import dao.ConsultationDao;
import dao.ScheduleDao;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Iterator;

/**
 * @author: Poh Qi Xuan
 * Consultation Management Control - Module 3
 * Manages patient consultations and arrange subsequent visit appointments
 */
public class ConsultationManagementControl {
    
    private ArrayBucketList<String, Consultation> consultations;
    private ArrayBucketList<String, Consultation> scheduledConsultations;
    private ConsultationDao consultationDao;
    private ScheduleDao scheduleDao;
    
    public ConsultationManagementControl() {
        this.consultations = new ArrayBucketList<String, Consultation>();
        this.scheduledConsultations = new ArrayBucketList<String, Consultation>();
        this.consultationDao = new ConsultationDao();
        this.scheduleDao = new ScheduleDao();
        loadConsultationData();
    }
    
    public void loadConsultationData() {
        try {
            consultations = consultationDao.findAll();
            Iterator<Consultation> consultationIterator = consultations.iterator();
            while (consultationIterator.hasNext()) {
                Consultation consultation = consultationIterator.next();
                if (consultation.getStatus() == Consultation.ConsultationStatus.SCHEDULED) {
                    scheduledConsultations.add(consultation.getConsultationId(), consultation);
                }
            }
        } catch (Exception exception) {
            System.err.println("Error loading consultation data: " + exception.getMessage());
        }
    }
    
    // Consultation Management Methods
    public boolean scheduleConsultation(Patient patient, Doctor doctor, 
                                      LocalDateTime consultationDate, String symptoms, 
                                      double consultationFee) {
        try {
            // Create new consultation without ID (will be generated by database)
            Consultation consultation = new Consultation(null, patient, doctor, 
                                                       consultationDate, symptoms, consultationFee);
            
            // Insert consultation and get the generated ID
            boolean consultationInserted = consultationDao.insertAndReturnId(consultation);
            if (!consultationInserted) {
                System.err.println("Failed to insert consultation");
                return false;
            }
            
            // Add to lists
            consultations.add(consultation.getConsultationId(), consultation);
            scheduledConsultations.add(consultation.getConsultationId(), consultation);
            
            return true;
        } catch (Exception exception) {
            System.err.println("Error scheduling consultation: " + exception.getMessage());
            return false;
        }
    }
    
    public boolean startConsultation(String consultationId) {
        try {
            Consultation consultation = findConsultationById(consultationId);
            if (consultation != null && consultation.getStatus() == Consultation.ConsultationStatus.SCHEDULED) {
                consultation.setStatus(Consultation.ConsultationStatus.IN_PROGRESS);
                
                // Update in database
                boolean updated = consultationDao.updateStatus(consultationId, Consultation.ConsultationStatus.IN_PROGRESS);
                if (!updated) {
                    System.err.println("Failed to update consultation status in database");
                    return false;
                }
                
                return true;
            }
            return false;
        } catch (Exception exception) {
            System.err.println("Error starting consultation: " + exception.getMessage());
            return false;
        }
    }
    
    public boolean completeConsultation(String consultationId, String diagnosis, 
                                      String treatment, String notes, LocalDateTime nextVisitDate) {
        try {
            Consultation consultation = findConsultationById(consultationId);
            if (consultation != null && consultation.getStatus() == Consultation.ConsultationStatus.IN_PROGRESS) {
                consultation.setDiagnosis(diagnosis);
                consultation.setTreatment(treatment);
                consultation.setNotes(notes);
                consultation.setNextVisitDate(nextVisitDate);
                consultation.setStatus(Consultation.ConsultationStatus.COMPLETED);
                
                // Update in database
                boolean updated = consultationDao.update(consultation);
                if (!updated) {
                    System.err.println("Failed to update consultation in database");
                    return false;
                }
                
                // Remove from scheduled consultations
                removeFromScheduledConsultations(consultation);
                
                return true;
            }
            return false;
        } catch (Exception exception) {
            System.err.println("Error completing consultation: " + exception.getMessage());
            return false;
        }
    }
    
    public boolean cancelConsultation(String consultationId) {
        try {
            Consultation consultation = findConsultationById(consultationId);
            if (consultation != null && consultation.getStatus() == Consultation.ConsultationStatus.SCHEDULED) {
                consultation.setStatus(Consultation.ConsultationStatus.CANCELLED);
                
                // Update in database
                boolean updated = consultationDao.updateStatus(consultationId, Consultation.ConsultationStatus.CANCELLED);
                if (!updated) {
                    System.err.println("Failed to update consultation status in database");
                    return false;
                }
                
                // Remove from scheduled consultations
                removeFromScheduledConsultations(consultation);
                
                return true;
            }
            return false;
        } catch (Exception exception) {
            System.err.println("Error cancelling consultation: " + exception.getMessage());
            return false;
        }
    }
    
    // Search and Retrieval Methods
    public Consultation findConsultationById(String consultationId) {
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getConsultationId().equals(consultationId)) {
                return consultation;
            }
        }
        return null;
    }
    
    public ArrayBucketList<String, Consultation> findConsultationsByPatient(String patientId) {
        ArrayBucketList<String, Consultation> patientConsultations = new ArrayBucketList<String, Consultation>();
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getPatient().getPatientId().equals(patientId)) {
                patientConsultations.add(consultation.getConsultationId(), consultation);
            }
        }
        return patientConsultations;
    }
    
    public ArrayBucketList<String, Consultation> findConsultationsByDoctor(String doctorId) {
        ArrayBucketList<String, Consultation> doctorConsultations = new ArrayBucketList<String, Consultation>();
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getDoctor().getDoctorId().equals(doctorId)) {
                doctorConsultations.add(consultation.getConsultationId(), consultation);
            }
        }
        return doctorConsultations;
    }
    
    public ArrayBucketList<String, Consultation> findConsultationsByDate(LocalDateTime date) {
        ArrayBucketList<String, Consultation> dateConsultations = new ArrayBucketList<String, Consultation>();
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getConsultationDate().toLocalDate().equals(date.toLocalDate())) {
                dateConsultations.add(consultation.getConsultationId(), consultation);
            }
        }
        return dateConsultations;
    }
    
    public ArrayBucketList<String, Consultation> getScheduledConsultations() {
        return scheduledConsultations;
    }
    
    public ArrayBucketList<String, Consultation> getCompletedConsultations() {
        ArrayBucketList<String, Consultation> completedConsultations = new ArrayBucketList<String, Consultation>();
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getStatus() == Consultation.ConsultationStatus.COMPLETED) {
                completedConsultations.add(consultation.getConsultationId(), consultation);
            }
        }
        return completedConsultations;
    }
    
    public ArrayBucketList<String, Consultation> getAllConsultations() {
        return consultations;
    }
    
    public int getTotalConsultations() {
        return consultations.getSize();
    }
    
    public int getScheduledConsultationsCount() {
        return scheduledConsultations.getSize();
    }
    
    // Reporting Methods
    public String generateConsultationReport() {
        StringBuilder report = new StringBuilder();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
        report.append("=== CONSULTATION REPORT ===\n");
        report.append("Total Consultations: ").append(getTotalConsultations()).append("\n");
        report.append("Scheduled Consultations: ").append(getScheduledConsultationsCount()).append("\n");
        report.append("Completed Consultations: ").append(getCompletedConsultations().getSize()).append("\n");
        report.append("Report Generated: ").append(LocalDate.now().format(dateFormatter)).append("\n\n");
        
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            report.append("Consultation ID: ").append(consultation.getConsultationId()).append("\n");
            report.append("Patient: ").append(consultation.getPatient().getFullName()).append("\n");
            report.append("Doctor: ").append(consultation.getDoctor().getFullName()).append("\n");
            report.append("Date: ").append(consultation.getConsultationDate().format(dateTimeFormatter)).append("\n");
            report.append("Status: ").append(consultation.getStatus()).append("\n");
            report.append("Fee: RM").append(consultation.getConsultationFee()).append("\n");
            report.append("----------------------------------------\n");
        }
        
        return report.toString();
    }
    
    public String generateConsultationHistoryReport() {
        StringBuilder report = new StringBuilder();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
        report.append("=== CONSULTATION HISTORY REPORT ===\n");
        report.append("Total Consultations: ").append(getTotalConsultations()).append("\n");
        report.append("Completed Consultations: ").append(getCompletedConsultations().getSize()).append("\n");
        report.append("Report Generated: ").append(LocalDate.now().format(dateFormatter)).append("\n\n");
        
        Iterator<Consultation> consultationIterator = consultations.iterator();
        while (consultationIterator.hasNext()) {
            Consultation consultation = consultationIterator.next();
            if (consultation.getStatus() == Consultation.ConsultationStatus.COMPLETED) {
                report.append("Consultation ID: ").append(consultation.getConsultationId()).append("\n");
                report.append("Patient: ").append(consultation.getPatient().getFullName()).append("\n");
                report.append("Doctor: ").append(consultation.getDoctor().getFullName()).append("\n");
                report.append("Date: ").append(consultation.getConsultationDate().format(dateTimeFormatter)).append("\n");
                report.append("Status: ").append(consultation.getStatus()).append("\n");
                report.append("Fee: RM").append(consultation.getConsultationFee()).append("\n");
                report.append("----------------------------------------\n");
            }
        }
        
        return report.toString();
    }
    
    private void removeFromScheduledConsultations(Consultation consultation) {
        Iterator<Consultation> scheduledIterator = scheduledConsultations.iterator();
        while (scheduledIterator.hasNext()) {
            Consultation scheduledConsultation = scheduledIterator.next();
            if (scheduledConsultation.getConsultationId().equals(consultation.getConsultationId())) {
                scheduledConsultations.remove(scheduledConsultation.getConsultationId());
                break;
            }
        }
    }

    // Scheduling utilities
    public ArrayBucketList<String, Schedule> getAvailableSchedulesByDate(LocalDate date) {
        ArrayBucketList<String, Schedule> available = new ArrayBucketList<String, Schedule>();
        try {
            ArrayBucketList<String, Schedule> all = scheduleDao.findAll();
            entity.DayOfWeek target = entity.DayOfWeek.valueOf(date.getDayOfWeek().name());
            for (Schedule schedule : all) {
                if (schedule.isAvailable() && schedule.getDayOfWeek() == target) {
                    available.add(schedule.getScheduleId(), schedule);
                }
            }
        } catch (Exception e) {
            System.err.println("Error loading schedules: " + e.getMessage());
        }
        return available;
    }

    public boolean isTimeWithinDoctorSchedule(String doctorId, LocalDate date, LocalTime time) {
        try {
            ArrayBucketList<String, Schedule> all = scheduleDao.findAll();
            entity.DayOfWeek target = entity.DayOfWeek.valueOf(date.getDayOfWeek().name());
            boolean within = false;
            for (Schedule schedule : all) {
                if (schedule.isAvailable() && schedule.getDoctorId().equals(doctorId) && schedule.getDayOfWeek() == target) {
                    LocalTime from = LocalTime.parse(schedule.getFromTime());
                    LocalTime to = LocalTime.parse(schedule.getToTime());
                    if (!time.isBefore(from) && !time.isAfter(to)) {
                        within = true;
                        break;
                    }
                }
            }
            return within;
        } catch (Exception e) {
            System.err.println("Error validating time within schedule: " + e.getMessage());
            return false;
        }
    }

    public boolean hasDoctorConsultationAt(String doctorId, LocalDateTime dateTime) {
        Iterator<Consultation> it = consultations.iterator();
        while (it.hasNext()) {
            Consultation c = it.next();
            if (c.getDoctor().getDoctorId().equals(doctorId) && c.getConsultationDate().equals(dateTime)) {
                return true;
            }
        }
        return false;
    }
} 